Table "cache" {
  "key" varchar(255) [pk, not null]
  "value" mediumtext [not null]
  "expiration" int [not null]

  Indexes {
    expiration [type: btree, name: "cache_expiration_index"]
  }
}

Table "cache_locks" {
  "key" varchar(255) [pk, not null]
  "owner" varchar(255) [not null]
  "expiration" int [not null]

  Indexes {
    expiration [type: btree, name: "cache_locks_expiration_index"]
  }
}

Table "failed_jobs" {
  "id" "bigint unsigned" [pk, not null, increment]
  "uuid" varchar(255) [unique, not null]
  "connection" text [not null]
  "queue" text [not null]
  "payload" longtext [not null]
  "exception" longtext [not null]
  "failed_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table "job_batches" {
  "id" varchar(255) [pk, not null]
  "name" varchar(255) [not null]
  "total_jobs" int [not null]
  "pending_jobs" int [not null]
  "failed_jobs" int [not null]
  "failed_job_ids" longtext [not null]
  "options" mediumtext
  "cancelled_at" int
  "created_at" int [not null]
  "finished_at" int
}

Table "jobs" {
  "id" "bigint unsigned" [pk, not null, increment]
  "queue" varchar(255) [not null]
  "payload" longtext [not null]
  "attempts" "tinyint unsigned" [not null]
  "reserved_at" "int unsigned"
  "available_at" "int unsigned" [not null]
  "created_at" "int unsigned" [not null]

  Indexes {
    queue [type: btree, name: "jobs_queue_index"]
  }
}

Table "migrations" {
  "id" "int unsigned" [pk, not null, increment]
  "migration" varchar(255) [not null]
  "batch" int [not null]
}

Table "password_reset_tokens" {
  "email" varchar(255) [pk, not null]
  "token" varchar(255) [not null]
  "created_at" timestamp
}

Table "personal_access_tokens" {
  "id" "bigint unsigned" [pk, not null, increment]
  "tokenable_type" varchar(255) [not null]
  "tokenable_id" "bigint unsigned" [not null]
  "name" text [not null]
  "token" varchar(64) [unique, not null]
  "abilities" text
  "last_used_at" timestamp
  "expires_at" timestamp
  "created_at" timestamp
  "updated_at" timestamp

  Indexes {
    expires_at [type: btree, name: "personal_access_tokens_expires_at_index"]
    (tokenable_type, tokenable_id) [type: btree, name: "personal_access_tokens_tokenable_type_tokenable_id_index"]
  }
}

Table "posts" {
  "id" "bigint unsigned" [pk, not null, increment]
  "post_title" varchar(255) [not null]
  "post_description" text [not null]
  "post_slug" varchar(255) [unique, not null]
  "post_status" varchar(255) [not null]
  "post_publish_date" timestamp
  "language" json
  "created_at" timestamp
  "updated_at" timestamp
  "deleted_at" timestamp
}

Table "sessions" {
  "id" varchar(255) [pk, not null]
  "user_id" "bigint unsigned"
  "ip_address" varchar(45)
  "user_agent" text
  "payload" longtext [not null]
  "last_activity" int [not null]

  Indexes {
    last_activity [type: btree, name: "sessions_last_activity_index"]
    user_id [type: btree, name: "sessions_user_id_index"]
  }
}

Table "users" {
  "id" "bigint unsigned" [pk, not null, increment]
  "user_fullname" varchar(255) [not null]
  "user_mobile" varchar(255) [not null]
  "email" varchar(255) [unique, not null]
  "email_verified_at" timestamp
  "password" varchar(255) [not null]
  "remember_token" varchar(100)
  "created_at" timestamp
  "updated_at" timestamp
}
